### ISSUE TITLE
About '$$' and '$'.

### ISSUE THREAD

**Issue by livc** [phillord/mathjax-latex#14]
inline mode doesn't work like:
$ \sum_1^n $

display mode works.
$$ \sum_1^n $$

Is this a bug?

**Comment by phillord** [comment]
No. The use of a single `$` for inline maths is not default mathjax syntax (even if it is for tex). See here:

http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-math-delimiters

**Comment by livc** [comment]
@phillord But I selected the option ?

![image](https://cloud.githubusercontent.com/assets/11692045/18808340/fd041e7a-8291-11e6-8a2f-0a42e62f0020.png)

**Comment by phillord** [comment]
That would look like `$latex \sum_1^n $`.
