### ISSUE TITLE
Compress config/default.js

### ISSUE THREAD

**Issue by rrrfer** [phillord/mathjax-latex#25]
Hello. Google PageSpeed service recommended to compress https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/config/default.js

Is it really?

**Comment by paulschreiber** [comment]
1. CDNJS already supports gzip compression.
2. If you have questions about he MathJax libraries themselves, talk to the MathJax team https://github.com/mathjax/MathJax — this repository is for WordPress plugin-specific issues.
