### ISSUE TITLE
Rendering in category view

### ISSUE THREAD

**Issue by pipedream** [phillord/mathjax-latex#27]
We have a site using mathjax-latex, and it works well in posts, but not in the snippets shown when viewing a category of post. It simply shows nothing or a blank space.
https://aiminghigh.aimssec.ac.za/category/lesson-activities/

**Comment by paulschreiber** [comment]
This is not a bug in MathJax-LaTeX.

WordPress' excerpts are plain text and do not include images, shortcodes, hyperlinks, etc.

If you wish to override this behaviour, you may be able do so with the `the_excerpt` filter:
https://developer.wordpress.org/reference/functions/the_excerpt/
