### ISSUE TITLE
vertical alignment

### ISSUE THREAD

**Issue by clausTue** [phillord/mathjax-latex#29]
Hello,

I am new to the plugin, and unexperienced in WordPress. I just activated the plugin, and notice the problem that the latex equations are displayed vertically above the typical line elevation.

See all equations [here](http://planetwater.org/2018/03/28/crisp-and-interval-based-conditional-probabilities/), and attached screenshot-close-up.

Is there a setting for the vertical alignment?

<img width="387" alt="line_elevation_latex_mathjax" src="https://user-images.githubusercontent.com/2693855/38111591-a9a2ffb0-339f-11e8-950b-4059f49d5f69.png">

**Comment by paulschreiber** [comment]
Your equations are being generated as PNGs. You'll need to write CSS to fix this. Something like this:
```css
.main img {
  vertical-align: -5px;
}
```
