### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by patrickFuerst** [phillord/mathjax-latex#34]
After installing mathjax as a wordpress plugin I get the following error.
And latex is not rendered. 
Any idea what to do ? 

MathJax.js?config&ver=1.3.10:19 Uncaught TypeError: this.params.config.split is not a function
    at Object.Config (MathJax.js?config&ver=1.3.10:19)
    at Function.execute (MathJax.js?config&ver=1.3.10:19)
    at cb (MathJax.js?config&ver=1.3.10:19)
    at Object.Process (MathJax.js?config&ver=1.3.10:19)
    at Object.Push (MathJax.js?config&ver=1.3.10:19)
    at MathJax.js?config&ver=1.3.10:19
    at MathJax.js?config&ver=1.3.10:19

**Comment by paulschreiber** [comment]
What's the URL of your page with this error?

**Comment by patrickFuerst** [comment]
Hey Paul, 
it's an internal page, so the url won't help. 
We are using Wordpress 4.9.8.  What kind of information could I provide to solve this ?

**Comment by paulschreiber** [comment]
Can you save the page as a web archive and upload it here? Be sure to erase any confidential information from the page before saving it.

**Comment by patrickFuerst** [comment]
I works now. After changing the Force load of Mathjax to true and then back again.
