### ISSUE TITLE
Parentheses in WordPress plugin info page

### ISSUE THREAD

**Issue by Alex-Jordan** [phillord/mathjax-latex#38]
I noticed at [the WP information page for this plugin](https://wordpress.org/plugins/mathjax-latex/) that the `\(...\)` in the documentation render as `(...)`. It might obscures that `\(...\)` can be used for inline input for anyone not already familiar with LaTeX.

**Comment by paulschreiber** [comment]
This seems like a bug in the wordpress.org readme parser. I've filed https://meta.trac.wordpress.org/ticket/4100.

**Comment by Alex-Jordan** [comment]
That makes sense. I'll close this issue here.

**Comment by paulschreiber** [comment]
WP folks say this is expected behaviour for Markdown.

**Comment by Alex-Jordan** [comment]
Maybe backticks in the readme would address the issue.
