### ISSUE TITLE
Regarding bug fixes

### ISSUE THREAD

**Issue by viru0** [phillord/mathjax-latex#48]
Hi there! 
I see that in inline math text when we type $$\therefore$$. It is not working. Showing error. 
Please fix it and  this plugin is not updated from last 5 months. 
The WordPress site shows "untested version" on the latest version of WP. 
Next, question- how to disable the Mathjax menu. 
Please update as soon as if possible.

**Comment by paulschreiber** [comment]
You have combined many comments into one issue. Each issue should be for a specific problem, and contain sufficient detail to reproduce the problem.

>I see that in inline math text when we type $$\therefore$$. It is not working. Showing error.

Please file a new ticket with the exact steps to reproduce and text of the error.

**Comment by viru0** [comment]
I see that in inline math text when we type $$\therefore$$. It is not working. Showing error.
Please fix it. 
Thanks.

**Comment by viru0** [comment]
This plugin is not updated from last 5 months.
The WordPress site shows "untested version" on the latest version of WP.
Please update as soon as if possible.
