### ISSUE TITLE
Compatibility with WordPress 6

### ISSUE THREAD

**Issue by grettke** [phillord/mathjax-latex#53]
Just upgraded my blog to WordPress v6.

The plugin is configured with 2.7.5.

This is my [test post](https://www.wisdomandwonder.com/emacs/10660/mathjax-support-in-org2blog) for the plugin.

It is working correctly as expected.

I'm happy to do more testing. 

What I am thinking is to create a page with a lot of examples on it.

**Comment by paulschreiber** [comment]
Updated README with #54.
