### ISSUE TITLE
Equation scaling in mobile devices

### ISSUE THREAD

**Issue by iouzzrj** [phillord/mathjax-latex#56]
Hi mathjax,
I'm using mathjax for math equation in my wordpress website. I like this plugin very much.
I have one question about the equation scaling in mobile deveices. You can see in the following image, I have a long equation. In desktop environment, the screen is wide enough for this equation. However, this is not the case for mobile device. For mobile device, wordpress block will change their layout, which include change the words layout and scale the image size down. However, for the equation, it will only consume the whitespace between equation and tag. Beyond that, the equation never scale its size down. My question is, is this behavior related to mathjax-latex? Can I make the equation the change the layout, e.g. from one line to two line, or just scale its size down?
Thank you.
![屏幕截图 2022-11-10 094357](https://user-images.githubusercontent.com/43952332/200980420-3be6e1d3-ad9e-41ee-9e30-d44eed2adc7a.png)

**Comment by paulschreiber** [comment]
Is this page public somewhere? Can you share a link?

**Comment by iouzzrj** [comment]
@paulschreiber 
Here's the link:
https://1193jf.com/brain-waves/

**Comment by paulschreiber** [comment]
@iouzzrj Looks like this a MathJax configuration change you can make: https://github.com/mathjax/MathJax/issues/2465
i.e. not specific to the plugin.
