### ISSUE TITLE
refresh latex rendering after page load (after displaying a latex string from an ajax load)

### ISSUE THREAD

**Issue by Reghyz** [phillord/mathjax-latex#62]
I asked this question on wp plugin support page, i ask it here too, i dont know if this plugin is still maintained..

I am loading and displaying LaTeX-formatted code with AJAX. This occurs after the page has initialized, so the code is not formatted properly. Is there a JavaScript function or event I can call after displaying my AJAX response to refresh the formatting?

**Comment by paulschreiber** [comment]
Ask the MathJax folks — this plugin is just a wrapper around their library.
